version: '2.4'

volumes:
  orsdata:

services:
  ors:
    ports:
      - '8080:8080'
      - '9001:9001'
    image: openrouteservice/openrouteservice:nightly
    user: '${UID:-0}:${GID:-0}'
    volumes:
      - orsdata:/home/ors/ors-core/data
      - ./ors/conf:/home/ors/ors-conf
      - ./ors/pbf:/home/ors/ors-core/pbf
    environment:
      - BUILD_GRAPHS=False # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - 'JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g'
      - 'CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost'
      - ORS_CONFIG=/home/ors/ors-conf/ors-config.json
